# Navigation Links

main:
  - name: Research
    weight: 10
  - name: Computational EM
    parent: Research
    url: /tags/computational-em/
    weight: 11
  - name: Time-varying EM
    parent: Research
    url: /tags/time-varying-em/
    weight: 12
  - name: Knot EM
    parent: Research
    url: /tags/knot-em/
    weight: 13
  - name: Blog
    url: /blog/
    weight: 20
  - name: Projects
    url: /projects/
    weight: 30
  - name: Volunteer
    url: /volunteer/
    weight: 40
  - name: CV
    url: /cv/
    weight: 50
  - name: Contact
    url: /#contact
    weight: 60
